bootstrap.servers=192.168.100.6:9092
plugin.path=/opt/kafka/libs
group.id=connect-cluster-mm2
config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
offset.flush.interval.ms=10000
rest.port=8083
rest.advertised.host.name=192.168.100.6
