# kafka-active002 — 사설 PLAINTEXT:9092 + 외부 EXTERNAL:9094(공인 광고)
# ACG에서 9094 TCP 허용.

process.roles=broker,controller
node.id=1
controller.quorum.voters=1@192.168.100.7:9093

listeners=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
advertised.listeners=PLAINTEXT://192.168.100.7:9092,EXTERNAL://223.130.154.172:9094
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

log.dirs=/var/lib/kafka/kraft-combined-logs

num.partitions=3
default.replication.factor=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

group.initial.rebalance.delay.ms=0
